name: Destroy Terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-2'

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Show AWS Credentials (for debugging)
        run: |
          echo "AWS Region: $AWS_DEFAULT_REGION"
          echo "AWS Access Key ID: ${AWS_ACCESS_KEY_ID:0:4}..."

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -input=false
        continue-on-error: false

      - name: Show Current State
        run: |
          cd terraform
          terraform state list
          terraform show

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -destroy -out=tfplan
        continue-on-error: false

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve
        continue-on-error: false
        timeout-minutes: 30 