name: Destroy Terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-2'

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply (to recreate state)
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy -auto-approve 