name: Destroy Terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-2'

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION

      - name: Terraform Init
        run: |
          cd terraform
          terraform init
        continue-on-error: false

      - name: Delete Kubernetes Services (LoadBalancers)
        run: |
          cd terraform
          echo "Fetching EKS cluster credentials..."
          aws eks update-kubeconfig --name Simple-App-Cluster --region us-east-2
          echo "Deleting all services of type LoadBalancer..."
          kubectl delete svc --all
        continue-on-error: true

      - name: Delete Node Groups
        run: |
          cd terraform
          echo "Destroying EKS node groups..."
          terraform destroy -target=module.eks.module.eks_managed_node_group["eks_nodes"] -auto-approve
          echo "Waiting for node groups to be fully terminated..."
          sleep 180

      - name: Delete EKS Cluster
        run: |
          cd terraform
          echo "Destroying EKS cluster and related resources.."
          terraform destroy -target=module.eks -auto-approve
          echo "Waiting for EKS cluster to be fully terminated.."
          sleep 180

      - name: Delete Remaining Infrastructure
        run: |
          cd terraform
          echo "Destroying remaining infrastructure..."
          terraform destroy -auto-approve
        timeout-minutes: 60
        
