name: Destroy Terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-2'

jobs:
  terraform_destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.1"

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION

      - name: Terraform Init
        run: |
          cd terraform
          terraform init
        continue-on-error: false

      - name: Delete Kubernetes Services (LoadBalancers)
        run: |
          cd terraform
          echo "Fetching EKS cluster credentials..."
          aws eks update-kubeconfig --name Simple-App-Cluster --region $AWS_DEFAULT_REGION
          echo "Deleting all services of type LoadBalancer..."
          kubectl delete svc --all
        continue-on-error: true

      - name: Terraform Plan Destroy
        run: |
          cd terraform
          echo "Running destroy plan to see what resources will be removed..."
          terraform plan -destroy -out=tfdestroyplan

      - name: Destroy All Resources
        run: |
          cd terraform
          echo "Destroying all infrastructure resources..."
          terraform apply -auto-approve tfdestroyplan
        timeout-minutes: 60
